#ifndef CYGTFeatures_H
#define CYGTFeatures_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// CYGTFeatures                                                               //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/CYGTFeatures_Base.h"
#include <TGNumberEntry.h>

class CYGWindow;


class CYGTFeatures : public CYGTFeatures_Base
{
protected:

private:
   CYGTFeatures(const CYGTFeatures &c); // not implemented
   CYGTFeatures &operator=(const CYGTFeatures &c); // not implemented

   TRootEmbeddedCanvas *fCanvas;

   TGNumberEntry *fNumberLow;
   TGNumberEntry *fNumberHigh;

public:
   CYGTFeatures(CYGWindow* window = 0):CYGTFeatures_Base(window)
   {
   }

   virtual ~CYGTFeatures()
   {
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(CYGTFeatures,0)
};

#endif   // CYGTFeatures_H
