#ifndef CYGTEventDisplay_H
#define CYGTEventDisplay_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// CYGTEventDisplay                                                           //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/CYGTEventDisplay_Base.h"
#include <TGNumberEntry.h>

class CYGWindow;
class TCanvas;

class CYGTEventDisplay : public CYGTEventDisplay_Base
{
 protected:
  
 private:
  CYGTEventDisplay(const CYGTEventDisplay &c); // not implemented
  CYGTEventDisplay &operator=(const CYGTEventDisplay &c); // not implemented
  
  TRootEmbeddedCanvas *fCanvas;
  TRootEmbeddedCanvas *fCanvasDig;

  TGNumberEntry *fNumberLow;
  TGNumberEntry *fNumberHigh;
  
 public:

 CYGTEventDisplay(CYGWindow* window = 0):CYGTEventDisplay_Base(window)
  {
  }
  
   virtual ~CYGTEventDisplay()
   {
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();


   ClassDef(CYGTEventDisplay,0)
};

#endif   // CYGTEventDisplay_H
